FROM dronehippie/base:amd64

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Drone Buildx" \
  org.opencontainers.image.vendor="Webhippie" \
  org.opencontainers.image.documentation="https://dronehippie.github.io/chglog/"

ENTRYPOINT ["/bin/drone-chglog"]
ADD bin/drone-chglog /bin/
